language: php
php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist
  - mysql -e 'create database phinx_test;'
  - cd $TRAVIS_BUILD_DIR

script:
  - composer check-all
