<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '2d32cef395235865ba9169aa5160ea9e82252760',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '2d32cef395235865ba9169aa5160ea9e82252760',
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.9.3',
            'version' => '0.9.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'reference' => 'ca57d18f028f84f777b2168cd1911b0dee2343ae',
            'dev_requirement' => false,
        ),
        'cakephp/cache' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cache',
            'aliases' => array(),
            'reference' => '0e95a17b118d900f362de07bff902fa147e51fb2',
            'dev_requirement' => false,
        ),
        'cakephp/collection' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/collection',
            'aliases' => array(),
            'reference' => '5667e755cfafe4b186f5f2a54121cf44cb86159e',
            'dev_requirement' => false,
        ),
        'cakephp/core' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/core',
            'aliases' => array(),
            'reference' => '716300a55ac86b7456e52258d3f50545545d2d6b',
            'dev_requirement' => false,
        ),
        'cakephp/database' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/database',
            'aliases' => array(),
            'reference' => 'a193b3f4f82497d64ce5bfdbfd659740f745ffcc',
            'dev_requirement' => false,
        ),
        'cakephp/datasource' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/datasource',
            'aliases' => array(),
            'reference' => 'accbe0c85552f384e587d73abdba1618c604b54d',
            'dev_requirement' => false,
        ),
        'cakephp/log' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/log',
            'aliases' => array(),
            'reference' => 'cf10bdcce4e78430a780edb2cc5b4b2b4719a65d',
            'dev_requirement' => false,
        ),
        'cakephp/utility' => array(
            'pretty_version' => '3.10.0',
            'version' => '3.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/utility',
            'aliases' => array(),
            'reference' => '51b0af31af3239f6141006bbd7cbc7b16aba40d6',
            'dev_requirement' => false,
        ),
        'ccxt/ccxt' => array(
            'pretty_version' => '1.53.65',
            'version' => '1.53.65.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ccxt/ccxt',
            'aliases' => array(),
            'reference' => '715a92ebbeb60d50c368ba5aef4f806356da3d43',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => 'd56bf6102915de5702778fe20f2de3b2fe570b5b',
            'dev_requirement' => true,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.13.0',
            'version' => '4.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '08e27c97e4c6ed02f37c5b2b20488046c8d90d75',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.4.0',
            'version' => '5.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'd2113d9b2e0e349796e72d2a63cf9319100382d2',
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'pretty_version' => 'v1.9.2',
            'version' => '1.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fzaninotto/faker',
            'aliases' => array(),
            'reference' => '848d8125239d7dbf8ab25cb7f054f1a630e68c2e',
            'dev_requirement' => false,
        ),
        'google/appengine-php-sdk' => array(
            'pretty_version' => '1.9.30',
            'version' => '1.9.30.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/appengine-php-sdk',
            'aliases' => array(),
            'reference' => '6bdf4bcb638782526a6969aa36528ac583cbc3da',
            'dev_requirement' => false,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.18.0',
            'version' => '1.18.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'reference' => '21dd478e77b0634ed9e3a68613f74ed250ca9347',
            'dev_requirement' => false,
        ),
        'google/cloud' => array(
            'pretty_version' => 'v0.136.0',
            'version' => '0.136.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/cloud',
            'aliases' => array(),
            'reference' => 'ac708f1d3945e3be367ebd47ba7491698724ca65',
            'dev_requirement' => false,
        ),
        'google/cloud-asset' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.1',
            ),
        ),
        'google/cloud-automl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.2',
            ),
        ),
        'google/cloud-bigquery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.16.0',
            ),
        ),
        'google/cloud-bigquery-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.2',
            ),
        ),
        'google/cloud-bigquerydatatransfer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.0',
            ),
        ),
        'google/cloud-bigtable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.4.3',
            ),
        ),
        'google/cloud-billing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.0',
            ),
        ),
        'google/cloud-common-protos' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.1',
            ),
        ),
        'google/cloud-container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.0',
            ),
        ),
        'google/cloud-core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.38.0',
            ),
        ),
        'google/cloud-data-catalog' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.0',
            ),
        ),
        'google/cloud-dataproc' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.1',
            ),
        ),
        'google/cloud-datastore' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.6',
            ),
        ),
        'google/cloud-debugger' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.0',
            ),
        ),
        'google/cloud-dialogflow' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.16.0',
            ),
        ),
        'google/cloud-dlp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.26.1',
            ),
        ),
        'google/cloud-error-reporting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.17.0',
            ),
        ),
        'google/cloud-firestore' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.14.1',
            ),
        ),
        'google/cloud-iot' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.2',
            ),
        ),
        'google/cloud-kms' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.10.2',
            ),
        ),
        'google/cloud-language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.22.5',
            ),
        ),
        'google/cloud-logging' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.20.1',
            ),
        ),
        'google/cloud-memcache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.1',
            ),
        ),
        'google/cloud-monitoring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.0.1',
            ),
        ),
        'google/cloud-oslogin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.1',
            ),
        ),
        'google/cloud-pubsub' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.26.0',
            ),
        ),
        'google/cloud-recaptcha-enterprise' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.1',
            ),
        ),
        'google/cloud-recommendations-ai' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.1.2',
            ),
        ),
        'google/cloud-recommender' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.0.4',
            ),
        ),
        'google/cloud-redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.0.3',
            ),
        ),
        'google/cloud-scheduler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.4.1',
            ),
        ),
        'google/cloud-secret-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.0.0',
            ),
        ),
        'google/cloud-security-center' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.8.1',
            ),
        ),
        'google/cloud-service-directory' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.1.4',
            ),
        ),
        'google/cloud-spanner' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.30.0',
            ),
        ),
        'google/cloud-speech' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.1',
            ),
        ),
        'google/cloud-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.22.0',
            ),
        ),
        'google/cloud-talent' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.13.1',
            ),
        ),
        'google/cloud-tasks' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.7.1',
            ),
        ),
        'google/cloud-text-to-speech' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.1',
            ),
        ),
        'google/cloud-trace' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.3',
            ),
        ),
        'google/cloud-translate' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.8.0',
            ),
        ),
        'google/cloud-videointelligence' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.9.3',
            ),
        ),
        'google/cloud-vision' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.1',
            ),
        ),
        'google/cloud-web-risk' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.6.1',
            ),
        ),
        'google/cloud-web-security-scanner' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.5.1',
            ),
        ),
        'google/common-protos' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/common-protos',
            'aliases' => array(),
            'reference' => 'c348d1545fbeac7df3c101fdc687aba35f49811f',
            'dev_requirement' => false,
        ),
        'google/crc32' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/crc32',
            'aliases' => array(),
            'reference' => 'a8525f0dea6fca1893e1bae2f6e804c5f7d007fb',
            'dev_requirement' => false,
        ),
        'google/gax' => array(
            'pretty_version' => 'v1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/gax',
            'aliases' => array(),
            'reference' => '30ca2be6125c8936e74ad17ec2b495bb26697a59',
            'dev_requirement' => false,
        ),
        'google/grpc-gcp' => array(
            'pretty_version' => '0.1.5',
            'version' => '0.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/grpc-gcp',
            'aliases' => array(),
            'reference' => 'bb9bdbf62f6ae4e73d5209d85b1d0a0b9855ff36',
            'dev_requirement' => false,
        ),
        'google/protobuf' => array(
            'pretty_version' => 'v3.17.3',
            'version' => '3.17.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/protobuf',
            'aliases' => array(),
            'reference' => 'ae9282cf11dd2933b7e71a611f9590f07d53d3f3',
            'dev_requirement' => false,
        ),
        'google/recaptcha' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/recaptcha',
            'aliases' => array(),
            'reference' => '614f25a9038be4f3f2da7cbfd778dc5b357d2419',
            'dev_requirement' => false,
        ),
        'grpc/grpc' => array(
            'pretty_version' => '1.39.0',
            'version' => '1.39.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grpc/grpc',
            'aliases' => array(),
            'reference' => '101485614283d1ecb6b2ad1d5b95dc82495931db',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '8e7d04f1f6450fef59366c399cfad4b9383aa30d',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'dc960a912984efb74d0a90222870c72c87f10c91',
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => '6f724d7e04606fd8adaa4e3bb381c3e9db09c946',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => '174395a901b5ba0925f1d790fa91bab531074b61',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '71312564759a7db5b789296369c1a264efc43aad',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '776f831124e9c62e1a2c601ecc52e776d8bb7220',
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.10.2',
            ),
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.7.7',
            'version' => '1.7.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => 'd178027d1e679832db9f38248fcc7200647dc2b7',
            'dev_requirement' => false,
        ),
        'odan/phinx-migrations-generator' => array(
            'pretty_version' => '4.6.1',
            'version' => '4.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../odan/phinx-migrations-generator',
            'aliases' => array(),
            'reference' => '7a8afe501520e322452bae2e3188756eafc7194a',
            'dev_requirement' => true,
        ),
        'opis/closure' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/closure',
            'aliases' => array(),
            'reference' => '06e2ebd25f2869e54a306dda991f7db58066f7f6',
            'dev_requirement' => false,
        ),
        'pear/console_table' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_table',
            'aliases' => array(),
            'reference' => '1930c11897ca61fd24b95f2f785e99e0f36dcdea',
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => 'bae7c545bef187884426f042434e561ab1ddb182',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.2.2',
            'version' => '5.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '069a785b2141f5bcf49f3e353548dc1cce6df556',
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0',
            'dev_requirement' => true,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'dd803df5ad7492e1b40637f7ebd258fee5ca7355',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.18.0',
            'version' => '1.18.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => '418cd304e8e6b417ea79c3b29126a25dc4b1170c',
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => 'd86dfc2e2a3cd366cee475e52c6bb3bbc371aa0e',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '7.0.15',
            'version' => '7.0.15.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => '819f92bba8b001d4363065928088de22f25a3a48',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => '28af674ff175d0768a5a978e6de83f697d4a7f05',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '2454ae1765516d20c4ffe103d85a58a9a3bd5662',
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '3.1.3',
            'version' => '3.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'reference' => '9c1da83261628cb24b6a6df371b6e312b3954768',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '8.5.20',
            'version' => '8.5.20.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => '9deefba183198398a09b927a6ac6bc1feb0b7b70',
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'reference' => 'ab2237657ad99667a5143e32ba2683c8029563d4',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.2.1',
            'version' => '4.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'fe665a03df4f056aa65af552a96e1976df8c8dae',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.2.1',
            ),
        ),
        'riimu/kit-phpencoder' => array(
            'pretty_version' => 'v2.4.1',
            'version' => '2.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../riimu/kit-phpencoder',
            'aliases' => array(),
            'reference' => 'ca6f004e1290aec7ef4bebf6c0807b30fcf981d7',
            'dev_requirement' => true,
        ),
        'rize/uri-template' => array(
            'pretty_version' => '0.3.3',
            'version' => '0.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rize/uri-template',
            'aliases' => array(),
            'reference' => '6e0b97e00e0f36c652dd3c37b194ef07de669b82',
            'dev_requirement' => false,
        ),
        'robmorgan/phinx' => array(
            'pretty_version' => '0.11.7',
            'version' => '0.11.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../robmorgan/phinx',
            'aliases' => array(),
            'reference' => '3cdde73e0c33c410e076108b3e1603fabb5b330d',
            'dev_requirement' => false,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => '1de8cd5c010cb153fcd68b8d0f64606f523f7619',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '1071dfcef776a57013124ff35e1fc41ccd294758',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '14f72dd46eaf2f2293cbe79c93cc0bc43161a211',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '4.2.4',
            'version' => '4.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => 'd47bbbad83711771f167c72d4e3f25f7fcc1f8b0',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '3.1.3',
            'version' => '3.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => '6b853149eab67d4da22291d36f5b0631c0fd856e',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => '474fb9edb7ab891665d3bfc6317f42a0a150454b',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => 'e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'reference' => '9b8772b9cbd456ab45d4a598d2dd1a1bced6363d',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => '367dcba38d6e1977be014dc4b22f47a484dac7fb',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => '31d35ca87926450c44eae7e2611d45a7a65ea8b3',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'reference' => '0150cfbc4495ed2df3872fb31b26781e4e077eb4',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'dev_requirement' => true,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v4.4.30',
            'version' => '4.4.30.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => 'd9ea72de055cd822e5228ff898e2aad2f52f76b0',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v4.4.30',
            'version' => '4.4.30.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'a3f7189a0665ee33b50e9e228c46f50f5acbed22',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v4.4.27',
            'version' => '4.4.27.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '517fb795794faf29086a77d99eb8f35e457837a7',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '46cd95797e9df938fdd2b03693b5fca5e64b01ce',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9174a3d80210dca8daa7f31fec659150bbeabfc6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'fba8933c384d6476ab14fb7b8526e5287ca7e010',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '1100343ed1a92e3a38f9ae122fc0eb21602547be',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => 'e66119f3de95efc359483f810c4c3e6436279436',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v1.1.9',
            'version' => '1.1.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'b776d18b303a39f56c63747bcb977ad4b27aca26',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v4.4.29',
            'version' => '4.4.29.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '3abcc4db06d4e776825eaa3ed8ad924d5bc7432a',
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'dev_requirement' => true,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '6964c76c7804814a842473e0c8fd15bab0f18e25',
            'dev_requirement' => true,
        ),
        'whichbrowser/parser' => array(
            'pretty_version' => 'v2.1.2',
            'version' => '2.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../whichbrowser/parser',
            'aliases' => array(),
            'reference' => 'bcf642a1891032de16a5ab976fd352753dd7f9a0',
            'dev_requirement' => false,
        ),
        'xendit/xendit-php' => array(
            'pretty_version' => '2.11.0',
            'version' => '2.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../xendit/xendit-php',
            'aliases' => array(),
            'reference' => '60150d6ad0ad99c93599c3fe2f4c4c56a9f5a946',
            'dev_requirement' => false,
        ),
    ),
);
